server:
   port: 8081
   servlet:
      context-path: '/boot-actuator'
info:
   application:
      name: 'actuator-test'
      java:
         source: ${java.version}
         target: ${java.version}   
management:
   server:
      port: 8082
   endpoints:
      web:
         base-path: '/management'
         exposure:
            include: '*' 
   endpoint:
      health:
         show-details: 'always'    
   health:
      status:
         order: 'FATAL, DOWN, OUT_OF_SERVICE, UNKNOWN, UP'
         http-mapping:
            FATAL: 500
   info:
      git:
         mode: 'full' 
   metrics:
      web:
         server:
            auto-time-requests: 'true'
            requests-metric-name: 'http.requests'                    
                                          